/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 chng.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chng.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.014']} position={[3.006, 0.371, 1.846]} scale={[1.855, 0.426, 0.897]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.011']} position={[0, 3.532, 0]} scale={[7, 3.5, 6]} />
      <group position={[-6.056, 2.037, -1.813]} scale={[1, 0.818, 3.149]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-6.582, 2.067, -1.852]} scale={[0.161, 0.805, 0.498]}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-6.163, 2.067, 0.456]} rotation={[0, 0.398, 0]} scale={[0.161, 0.805, 0.498]}>
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['Material.004']} />
      </group>
      <mesh geometry={nodes.Plane003.geometry} material={materials['Material.003']} position={[-5.53, 2.045, -1.132]} rotation={[0, -0.273, 0]} scale={[0.197, 0.342, 0.614]} />
      <group position={[-4.443, 1.226, -1.499]} rotation={[0, -1.192, 0]} scale={[0.571, 0.768, 0.768]}>
        <mesh geometry={nodes.Plane004_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane004_2.geometry} material={materials['Material.005']} />
      </group>
      <group position={[-5.975, 2.666, -3.926]} rotation={[0, 0.334, 0]} scale={[0.753, 0.632, 0.373]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.007']} />
      </group>
      <group position={[-5.518, 2.073, -2.391]} rotation={[0, 0.516, 0]} scale={[0.183, 0.035, 0.083]}>
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube002_3.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube002_4.geometry} material={materials['Material.010']} />
      </group>
      <group position={[2.981, 0.953, -5.368]} scale={[2.638, 0.106, 0.641]}>
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['Material.013']} />
      </group>
      <group position={[3.006, 2.444, -5.833]} rotation={[Math.PI / 2, 0, 0]} scale={[1.726, 1, 0.801]}>
        <mesh geometry={nodes.Plane005_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane005_2.geometry} material={materials['Material.012']} />
      </group>
    </group>
  )
}

useGLTF.preload('/chng.glb')
